name: "naive benchmarks"

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    name: "naive benchmarks"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json, opcache, apcu
          coverage: none

      - name: "caching dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "installing dependencies"
        run: "composer install --no-interaction --no-progress --ignore-platform-req php"

      - name: "running naive benchmarks"
        run: php "-dapc.enable=1" "-dapc.enable_cli=1" bin/naive-benchmark.php

      - name: "running naive benchmarks ( opcache=enabled )"
        run: php "-dopcache.enable_cli=yes" "-dopcache.enable=yes" "-dapc.enable=1" "-dapc.enable_cli=1" bin/naive-benchmark.php

      - name: "running naive benchmarks ( opcache=enabled,jit=1235 )"
        run: php "-dopcache.jit=1235" "-dopcache.enable_cli=yes" "-dopcache.enable=yes" "-dapc.enable=1" "-dapc.enable_cli=1" bin/naive-benchmark.php
